{% set name = "kmodes" %}
{% set version = "0.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kmodes-{{ version }}.tar.gz
  sha256: 1ed5c2bee2501974c0766f9816f3baf70c2c71d8c9053e65474ecc977d39023e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - joblib >=0.11
    - numpy >=1.10.4
    - python >=3.6
    - scikit-learn >=0.22.0
    - scipy >=0.13.3
    # until scipy is hotfixed
    - numpy <1.23.0

test:
  imports:
    - kmodes
    - kmodes.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nicodv/kmodes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python implementations of the k-modes and k-prototypes clustering algorithms for clustering categorical data.
  doc_url: https://pypi.org/project/kmodes/
  dev_url: https://github.com/nicodv/kmodes

extra:
  recipe-maintainers:
    - mxr-conda
