{% set name = "kmodes" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 097dc2435044a095a9ab134bf3cfb0a29c36955dc9c8a473fd0e9b53f91081e5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - joblib
    - numpy >=1.10.4
    - python
    - scikit-learn
    - scipy

test:
  imports:
    - kmodes
    - kmodes.util

about:
  home: https://github.com/nicodv/kmodes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python implementations of the k-modes and k-prototypes clustering algorithms for clustering categorical data.
  doc_url: https://pypi.org/project/kmodes/
  dev_url: https://github.com/nicodv/kmodes

extra:
  recipe-maintainers:
    - oblute
    - ndmaxar
    - rluria14
